### ISSUE TITLE
[Request] Caddyfile

### ISSUE THREAD

**Issue by John-S4** [AntCMS-org/AntCMS#28]
There are configs for nginx and Lighttpd as well as the 'standard' Apache, it would be nice if there was also a config to use AntCMS on Caddy.

**Comment by BelleNottelling** [comment]
There is now a simple [caddyfile](https://github.com/AntCMS-org/AntCMS/blob/main/configs/caddyfile) for AntCMS.

It works as expected with the exception of ETags where the browser sending a matching `If-None-Match` header and AntCMS responding with a 304 code & empty body results in the Caddy server not sending a response back to the browser.

For now, AntCMS will [simply not send](https://github.com/AntCMS-org/AntCMS/blob/main/src/AntCMS/AntCMS.php#L165) ETag headers when paired with Caddy. Other functionality like automatic asset compression works as intended though and so should image compression once I've implemented that.
